---
# Entry point for the CI Framework tool.
# Running by this playbook, and providing the needed information, you will
# be able to deploy various scenarios based on EDPM.
# Note that this playbook *must* be called from within
# openstack-k8s-operators/install_yaml repository in order to leverage its
# own methods.

- hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: true
  roles:
    - name: ci_setup
    - name: repo_setup

- name: Run pre-infra hooks
  vars:
    hooks: "{{ pre_infra | default([]) }}"
  ansible.builtin.import_playbook: ci_framework/playbooks/hooks.yml

- name: Import infra entrypoint playbook
  ansible.builtin.import_playbook: ci_framework/playbooks/infra-entry.yml

- name: Run post-infra hooks
  vars:
    hooks: "{{ post_infra | default([]) }}"
  ansible.builtin.import_playbook: ci_framework/playbooks/hooks.yml

- name: Run pre-package-build hooks
  vars:
    hooks: "{{ pre_package_build | default([]) }}"
  ansible.builtin.import_playbook: ci_framework/playbooks/hooks.yml

- name: Import package build playbook
  ansible.builtin.import_playbook: ci_framework/playbooks/build-packages.yml

- name: Run post-package-build hooks
  vars:
    hooks: "{{ post_package_build | default([]) }}"
  ansible.builtin.import_playbook: ci_framework/playbooks/hooks.yml

- name: Run pre-container-build hooks
  vars:
    hooks: "{{ pre_container_build | default([]) }}"
  ansible.builtin.import_playbook: ci_framework/playbooks/hooks.yml

- name: Import package build playbook
  ansible.builtin.import_playbook: ci_framework/playbooks/build-containers.yml

- name: Run post-container-build hooks
  vars:
    hooks: "{{ post_container_build | default([]) }}"
  ansible.builtin.import_playbook: ci_framework/playbooks/hooks.yml

- name: Run pre-deploy hooks
  vars:
    hooks: "{{ pre_deploy | default([]) }}"
  ansible.builtin.import_playbook: ci_framework/playbooks/hooks.yml

- name: Import package build playbook
  ansible.builtin.import_playbook: ci_framework/playbooks/deploy-edpm.yml

- name: Run post-deploy hooks
  vars:
    hooks: "{{ post_deploy | default([]) }}"
  ansible.builtin.import_playbook: ci_framework/playbooks/hooks.yml

- name: Gather logs and related data
  ansible.builtin.import_playbook: ci_framework/playbooks/logging.yml
