---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Start and enable libvirt service
  ansible.builtin.service:
    name: libvirtd
    state: started
    enabled: yes

- name: Check libvirt group exists
  block:
    - name: Get libvirt group users
      ansible.builtin.getent:
        database: group
        key: libvirt
  rescue:
    - name: Add libvirt group if not exists
      ansible.builtin.group:
        name: libvirt
        state: present
      become: true

- name: Get libvirt group users
  ansible.builtin.getent:
    database: group
    key: libvirt
  register: libvirt_group_users

- name: Add user if not exists in libvirt group
  ansible.builtin.user:
    name: "{{ cifmw_libvirt_manager_user }}"
    groups: libvirt
    append: yes yes
  when: "{{ cifmw_libvirt_manager_user }}' not in ansible_facts.getent_group['libvirt']"
  become: true

- name: Check virsh version
  ansible.builtin.command: virsh --connect qemu:///system --version
