---
# Configure base system to match centos
cifmw_repo_setup_os_release: 'centos'
cifmw_repo_setup_dist_major_version: 9
cifmw_use_libvirt: true
cifmw_use_crc: true
cifmw_rhol_crc_use_installyamls: true
