- hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Ensure libvirt is present/configured
      when:
        - cifmw_use_libvirt is defined
        - cifmw_use_libvirt | bool
      ansible.builtin.include_role:
        name: libvirt_manager
    - name: Prepare CRC
      when:
        - cifmw_use_crc is defined
        - cifmw_use_crc | bool
      ansible.builtin.include_role:
        name: rhol_crc
# TODO: vms, build-pkg-container
    - name: Create compute node
      when:
        - cifmw_use_libvirt is defined
        - cifmw_use_libvirt | bool
      block:
        - name: Run install_yamls make commands
          ci_make:
            output_dir: ~/ci-framework/artifacts
            chdir: ../
            target: edpm_compute
        - name: Configure repositorirs on compute
          ci_make:
            output_dir: ~/ci-framework/artifacts
            chdir: ../
            target: edpm_compute_repos
